### PR TITLE
merge more changes

### PR DESCRIPTION
**Pull request by legoboyvdlp**

### CODE REVIEW

**Comment by AlessandroMenti** [comment]
Thanks again for the work - there are two points that need some fixing:
1. it seems you have reverted the license and indentation change added in merge request #1 - please add them again;
2. I don't think we can distribute the charts as well (they are not licensed under the GPL) - maybe we could add a note stating where the user might download them?

**Comment by legoboyvdlp** [comment]
Youpsies...

**Comment by legoboyvdlp** [comment]
Right, @ElGaton -- this is ready

**Comment by AlessandroMenti** [comment]
I've [merged your pull request manually](https://github.com/ElGaton/festival-flightgear-may-2016/commit/74c09881852dfd0bb43b5a6f8ae3a18d91d0c7b4) so as not to store the charts in the repository. Thanks again for your work!

**Pull request closed without merging**
