### PR TITLE
initial commit -- old fashioned SIDS

### PR DESCRIPTION
**Pull request by legoboyvdlp**

### CODE REVIEW

**Comment by AlessandroMenti** [comment]
Thanks for the work - could you just perform the following corrections:
1. relicense the work under the "GPL 2 or later" (OpenRadar uses the GPLv3, if you choose only GPL 2 I'll be unable to submit your work upstream);
2. correct the indentation of the XML tags.

**Comment by legoboyvdlp** [comment]
Roger.

**Comment by legoboyvdlp** [comment]
Right, there we go. Should be fine now.

**Comment by AlessandroMenti** [comment]
Looks good. Thanks for your work!

**Pull request merged**
